### ISSUE TITLE
Windows : Import archive does not work

### ISSUE THREAD

**Issue by jbgury** [libreosteo/LibreOsteo#200]
When using the restore archive on the assistant at first usage, using a valid archive does not work on windows.
It fails and in the log the error is : 
```
Load a dump from a sent file.
Dump file was persisted for future loading.
Signals were disactivated, perform clearing of the database
Load the fixture from path : C:\Windows\TEMP\dump.json
Import failed
Traceback (most recent call last):
  File "C:\Users\jb\Libreosteo\libreosteoweb\api\views.py", line 756, in post
  File "C:\Users\jb\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 131, in call_command
  File "C:\Users\jb\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 330, in execute
  File "C:\Users\jb\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\commands\loaddata.py", line 69, in handle
  File "C:\Users\jb\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\commands\loaddata.py", line 135, in loaddata
  File "C:\Users\jb\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 110, in write
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by jbgury** [comment]
Cause : 
django changed the implementation of load_data and write on the stdout for "tracing" purpose : 
(see https://github.com/django/django/blob/stable/1.11.x/django/core/management/commands/loaddata.py#L133 and the base class : https://github.com/django/django/blob/stable/1.11.x/django/core/management/base.py#L201 )
When the application is frozen (by cxFreeze), the sys.stdout does not exist and is None.
