### ISSUE TITLE
Résidu de bower avec docker

### ISSUE THREAD

**Issue by littlejo** [libreosteo/LibreOsteo#228]
Quand j'essaie de lire un fichier que j'ai uploadé, j'ai cette erreur là en log :
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 109, in get_exception_response
    response = callback(request, **dict(param_dict, exception=exception))
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/defaults.py", line 47, in page_not_found
    body = template.render(context, request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 143, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 111, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 89, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/usr/local/lib/python3.6/site-packages/compressor/cache.py", line 104, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/compressor/base.py", line 200, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/compressor/base.py", line 194, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/usr/local/lib/python3.6/site-packages/compressor/js.py", line 17, in split_contents
    filename = self.get_filename(basename)
  File "/usr/local/lib/python3.6/site-packages/compressor/base.py", line 162, in get_filename
    self.finders and " or with staticfiles." or "."))
compressor.exceptions.UncompressableFileError: 'bower_components/angular/angular.min.js' could not be found in the COMPRESS_ROOT '/Libreosteo/static' or with staticfiles.

Est-ce qu'il y a ce bug aussi dans la version normal de libreosteo ?
Sinon qu'est-ce que j'ai manqué ?

**Comment by jbgury** [comment]
Normalement, le chemin bower_components n'existe plus. 
Les fichiers [package.json](https://github.com/libreosteo/Libreosteo/blob/master/package.json#L15) ne mentionnent que _node_modules/@components_
**master** et branche **develop** sont à jour. Peux tu vérifier dans ton image Docker ?
